# Fichero de configuración para los contenedores del cliente de la aplicación CarShare
version: "3.7"
services:
  # Crea un proxy inverso
  carshare-clientproxy:
    # Imagen base para generar el contenedor
    image: jwilder/nginx-proxy
    # Nombre asignado al contenedor
    container_name: carshare-clientproxy
    # Puertos abiertos para acceder al contenedor
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - carshare-client
    privileged: true

  # Crea un contenedor con la api de la aplicación
  carshare-client:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    build: .
    # Nombre asignado al contenedor
    container_name: carshare-client
    # Variable de entorno para el contendor
    environment:
      # Esta ruta debe estar incluida en el fichero hosts del anfitrión
      - VIRTUAL_HOST=carshare.client.local
    # Para la versión de desarrollo se mapea la carpeta con una local
    volumes:
      - ./:/usr/src/app
    networks:
      - carshare-client
    depends_on:
      - carshare-clientproxy
    # command: sh -c "npm install"


networks:
    carshare-client:
        driver: bridge
