# @author Rodrigo Navas
version: "3.8"
services:
  # # Crea un proxy inverso
  reverseproxy-rueda:
    # Imagen base para generar el contenedor
    image: jwilder/nginx-proxy
    # Nombre asignado al contenedor
    container_name: reverseproxy-rueda
    # Puertos abiertos para acceder al contenedor
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    privileged: true
  # Crea un contenedor con la api de la aplicación
  rueda-cliente:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    build: .
    # Nombre asignado al contenedor
    container_name: rueda-cliente
    # Variable de entorno para el contendor
    environment:
      # Esta ruta debe estar incluida en el fichero hosts del anfitrión
      - VIRTUAL_HOST=client-ruedas.com
      - VIRTUAL_PORT=4200
    # Para la versión de desarrollo se mapea la carpeta con una local
    volumes:
      - ./:/app/
    depends_on:
      - reverseproxy-rueda
